import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Layout, { nomeSito } from "../components/layout";
import utilStyles from '../styles/utils.module.css'

export default function Home() {
  return (
    <Layout home>
      <div className={styles.container}>
        <Head>
          <title>{nomeSito}</title>
          <h1>Template per gli articoli in vendita</h1>
          {/* <meta name="description" content="Generated by create next app" /> */}
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <h2>Tutti i template per gli articoli:</h2>
          <p>
            <Link href="articleTemplate">
              <a className={utilStyles.colorInherit}>Visualizza template 1</a>
            </Link>
            {/* aggiungere altri template */}
          </p>
        </main>
      </div>
    </Layout>
  )
}
